version: '3'
services:
   php:
    container_name: magento_php
    image: php:7.4-fpm-alpine
    restart: unless-stopped
    volumes:
        - ./magento/:/var/www/magento
        - ./php/conf/php.ini:/usr/local/etc/php/php.ini
        - ./magento:/app:cached
    expose:
        - "9000"
    environment:
         - WEB_ALIAS_DOMAIN=hanatyoma.fun
         - WEB_DOCUMENT_ROOT=/app/pub
         - PHP_DATE_TIMEZONE=EST
         - PHP_DISPLAY_ERRORS=1
         - PHP_MEMORY_LIMIT=2048M
         - PHP_MAX_EXECUTION_TIME=300
         - PHP_POST_MAX_SIZE=500M
         - PHP_UPLOAD_MAX_FILESIZE=1024M
   nginx:
      container_name: magento_nginx
      image: nginx:stable-alpine
      restart: unless-stopped
      volumes:
         - ./magento/:/var/www/magento
         - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
         - ./nginx/conf.d:/etc/nginx/conf.d:ro
      ports:
         - "80:80"
         - "443:443"
         - "32823:22"
   db:
    container_name: magento_mariadb
    image: mariadb:10.5.10
    restart: always
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=magento_password
      - MYSQL_DATABASE=magento_db
      - MYSQL_USER=devmagento
      - MYSQL_PASSWORD=magento_password
   phpmyadmin:
      container_name: magento_phpmyadmin
      restart: always
      image: phpmyadmin/phpmyadmin:latest
      environment:
         - MYSQL_ROOT_PASSWORD=magento_password
         - MYSQL_USER=devmagento
         - MYSQL_PASSWORD=magento_password
      ports:
         - "8080:80"
      links:
         - mysql:db
      depends_on:
         - db
networks:
   default:
      external:
         name: www_magento_network
            
